macos_instance:
  image: ghcr.io/cirruslabs/macos-runner:sonoma

task:
  script: |
    curl https://mise.run | sh
    ~/.local/bin/mise install
    ~/.local/bin/mise x -- tuist install
    ~/.local/bin/mise x -- tuist test -d "iPhone 16 Pro"